spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: projectTwo
      port: 27017
      host: localhost
      auto-index-creation: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1KB
      max-file-size: 200KB
      max-request-size: 200KB

## Enable multipart uploads
#spring.servlet.multipart.enabled=true
## Threshold after which files are written to disk.
#spring.servlet.multipart.file-size-threshold=1KB
## Max file size.
#spring.servlet.multipart.max-file-size=200KB
## Max Request Size
#spring.servlet.multipart.max-request-size=200KB
local:
  folders:
    baseWorkspace: ./workspaces/
  files:
    taskDefinition: /task_definition.yml
    taskSummaryResult: /test_results/test_summary.txt
