### get user by id
GET http://localhost:8080/users/1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### add new user
POST http://localhost:8080/users
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "id": "2TEST",
  "email": "rafal@gmail.com",
  "name": "Rafal Nowak",
  "password": "userPass",
  "roles": ["STUDENT"]
}

### get user by email
GET http://localhost:8080/users/2TEST
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

